import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from '@/components/Header';
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.3/dist/quill.snow.css" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
